"""create message

Revision ID: 9423f75e17a3
Revises: d32a3be47902
Create Date: 2026-04-20 23:22:56.241952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9423f75e17a3'
down_revision: Union[str, Sequence[str], None] = 'd32a3be47902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('admin_message_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('user_message_id', sa.String(), nullable=True))
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'user_message_id')
    op.drop_column('messages', 'admin_message_id')
    # ### end Alembic commands ###
